//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCS
    {
        public int PcID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Mobo { get; set; }
        public string RAM { get; set; }
        public string HDD { get; set; }
        public string Process { get; set; }
        public string ImgUrl { get; set; }
    }
}
